### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by TrafalgarDLaw2018** [altinselimi/kalendar#138]
After cloning, installing & fixing this projects dependencies i still can not run it on its own for Win10. 
What am i missing here? 

D:\Uni\Master\IUI\Kalendar\kalendar>npm run serve 

> kalendar-vue@2.2.1 serve
> vue-cli-service serve src/serve-dev.js

 INFO  Starting development server...
 ERROR  ValidationError: Progress Plugin Invalid Options

        options should NOT have additional properties
        options should NOT have additional properties
        options should NOT have additional properties
        options should pass "instanceof" keyword validation
        options should match exactly one schema in oneOf

ValidationError: Progress Plugin Invalid Options

options should NOT have additional properties
options should NOT have additional properties
options should NOT have additional properties
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

    at validateOptions (D:\Uni\Master\IUI\Kalendar\kalendar\node_modules\webpack\node_modules\schema-utils\src\validateOptions.js:32:11)
    at new ProgressPlugin (D:\Uni\Master\IUI\Kalendar\kalendar\node_modules\webpack\lib\ProgressPlugin.js:62:3)
    at new Progress (D:\Uni\Master\IUI\Kalendar\kalendar\node_modules\progress-webpack-plugin\index.js:25:21)
    at new progressPlugin (D:\Uni\Master\IUI\Kalendar\kalendar\node_modules\progress-webpack-plugin\index.js:127:10)
    at D:\Uni\Master\IUI\Kalendar\kalendar\node_modules\webpack-chain\src\Plugin.js:14:18
    at module.exports.toConfig (D:\Uni\Master\IUI\Kalendar\kalendar\node_modules\webpack-chain\src\Plugin.js:78:22)
    at D:\Uni\Master\IUI\Kalendar\kalendar\node_modules\webpack-chain\src\Config.js:129:63
    at Array.map (<anonymous>)
    at module.exports.toConfig (D:\Uni\Master\IUI\Kalendar\kalendar\node_modules\webpack-chain\src\Config.js:129:40)
    at Service.resolveWebpackConfig (D:\Uni\Master\IUI\Kalendar\kalendar\node_modules\@vue\cli-service\lib\Service.js:277:34)

**Comment by altinselimi** [comment]
It seems like you have some ESLint issues, can you try reproducing your issue in codesandbox ?
